plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'random-keys-survival-forge'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client { workingDirectory project.file('run') }
        server { workingDirectory project.file('run-server'); args '--nogui' }
    }
}

repositories { mavenCentral() }

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand 'version': project.version }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title': 'Random Keys Survival',
                'Specification-Vendor': 'Ray20123315',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'Ray20123315'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
